all:
	python ../../src/profiler_formatter_script.py -i ./files/JHy_profiler_update_21_14-29-42.json -o ./files/JHy_profiler_update_21_14-29-42.txt
	python ../../src/profiler_formatter_script.py -i ./files/JHy_profiler_update_21_14-29-42.json -o ./files/JHy_profiler_update_21_14-29-42.csv -f CSVFormatter

