all:
	python ../../src/profiler_formatter_script.py -i ./files/JHy_profiler_update_21_14-29-42.json -o ./files/JHy_profiler_update_21_14-29-42.txt
	python ../../src/profiler_formatter_script.py -i ./files/JHy_profiler_update_21_14-29-42.json -o ./files/JHy_profiler_update_21_14-29-42.csv -f CSVFormatter
	python ../../src/profiler_formatter_script.py -i ./files/JHy_python_update_07_19-46-44.json

